### ISSUE TITLE
B3文档内容缺少\n提示无法发送

### ISSUE THREAD

**Issue by SKlayer** [Bytom/B3-Mimic#2]
所有json stratum结束必须要有\n否则无法发送

**Comment by HAOYUatHZ** [comment]
对不起没太看明白问题  可以详细讲解一下吗

现在可以连上蚁池挖矿，普通电脑 一般 0.02~0.2 BTM/h 吧
改一下 login (到蚁池注册一个 矿工id) 就可以了～
