### ISSUE TITLE
这个配置文件在哪弄？？？

### ISSUE THREAD

**Issue by wshn13** [Bytom/B3-Mimic#3]
这个配置文件在哪哪？？？

**Comment by HAOYUatHZ** [comment]
改一下  login (到蚁池注册一个 矿工id) 就可以了～

现在可以连上蚁池挖矿，普通电脑 一般  0.02~0.2 BTM/h 吧

**Comment by wshn13** [comment]
我发现我修改了这个 send_msg := `{"method": "login", "params": {"login": "XXXXXX", "pass": "123", "agent": "bmminer/2.0.0"}, "id": 1222}`
id 随便填都可以成功登陆 这个有问题吧……

**Comment by ChrisLinn** [comment]
id 是 msg sequence  这个不重要
login对了就可以
pass也不验证的
你可以去蚁池看看收益如何

**Comment by wshn13** [comment]
@ChrisLinn 我随便写的login: XXXXXXXX 都可以通过验证啊 这个用户名真的存在？   另外login的用户名是自己的邮箱地址吗？ 子账户设置没有办法添加btm币 只能是btc和bch，这个怎么破？

**Comment by HAOYUatHZ** [comment]
https://www.antpool.com/
左上角可以选 bytom

login 可能正好存在
但是如果你不填自己的就白给别人挖了
