### ISSUE TITLE
请问你最近是否修复了一个newdiff相关难度的bug

### ISSUE THREAD

**Issue by J0hnn4J1ang** [Bytom/B3-Mimic#8]
感觉你fix这个后，我的性能达到了质的提升，请问fix之前的下面这句是否错误的提升了难度？
newDiff = new(big.Int).Mul(difficulty.CompactToBig(bh.Bits), newDiff)

**Comment by 0xmountaintop** [comment]
不是的，其实fix 之前的难度更低，但是逻辑不对，所以是错误的提交
